sparta/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('admin/', admin.site.urls),
    path('user', include('user.urls') ),


]

user/urls.py
from django.urls import path
from user import views

app_name = 'user'

urlpatterns = [
    
    path('signup/', views.signup, name='signup' ),

]

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    profile = models.TextField(max_length=500, blank=True)
    telnumber = models.IntegerField(max_length=500, blank=False)
    address = models.TextField(max_length=500, blank=True)

user/views.py
import re
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import User

# Create your views here.

def signup(request):
    if request.method == 'GET':        
        return render(request, 'signup.html' )
    elif request.method == 'POST':
        username = request.POST.get('username') 
        password = request.POST.get('password')
        passwordcheck = request.POST.get('passwordcheck')
        if password == passwordcheck:
            User.objects.create_user(username = username, password = password)
            return redirect('회원가입 완료')
        else :
            return HttpResponse('비밀번호 확인 틀렸습니다')

user/templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Login</title>
</head>
<body>
  django sparta 프로젝트의 메인 페이지입니다!
  <h2>Log In</h2>
  <form action="{% url 'user:signup' %}"  method="post"  >
  {% csrf_token %}
  <input type="text" name="username">아이디</input></br>
  <input type="text" name="password">비밀번호</input></br>
  <input type="text" name="phone">핸드폰번호</input></br>
  <input type="text" name="address">주소</input></br>
  <button type="submit">회원가입</button>
  </form>
</body>
</html>